### ISSUE TITLE
Getting started with Tabulator

### ISSUE THREAD

**Issue by isapir** [lekoala/formidable-elements#1]
Hi,

Is there a simple example for getting started with Tabulator-Grid?  Say that I have a simple table that I want to convert to Tabulator-Grid: 

```
<table id="sheet1">
    <tr>
        <th>Column A</th>
        <th>Column B</th>
    </tr>
    <tr>
        <td>Cell A-1</td>
        <td>Cell B-1</td>
    </tr>
        <tr>
        <td>Cell A-2</td>
        <td>Cell B-2</td>
    </tr>
</table>

<script type="text/javascript" src="tabulator-grid.min.js">
```

What would be the JavaScript code to turn that into an Editable table?

Thank you!

**Comment by lekoala** [comment]
There is plenty here

https://github.com/lekoala/formidable-elements/blob/master/demo/tabulator-grid.html

config options are exactly the same as tabulator, you can just pass that as a json string in data-config

**Comment by isapir** [comment]
Thank you
